### PR TITLE
Update to error handling

### PR DESCRIPTION
**Pull request by ericvicenti**
The DO api now uses `error_message` to describe errors.

### CODE REVIEW

**Comment by enzy** [comment]
I can't find it in the oficial docs, that's a shame.

Thank you for contribution, Eric!

**Comment by pahans** [comment]
please publish this to npm.

**Comment by ericvicenti** [comment]
@pahans , feel free to use the version in my repo in the meantime

```
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "digitalocean-api": "git+https://github.com/ericvicenti/digitalocean-api#master"
  }
}
```

**Comment by enzy** [comment]
@pahans Sorry for delay, just published to npm.

**Comment by pahans** [comment]
@enzy thank you.

**Pull request merged**
